plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.google.cloud.tools.jib' version '3.4.5'
}


jib {
    from {
        image = "openjdk:21-jdk-slim"
    }
    to {
        image = project.findProperty("dockerImageName")
        tags = ["latest"]
        auth {
            username = project.findProperty("dockerUsername")
            password = project.findProperty("dockerPassword")
        }
    }
}

group = 'com.baedal'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {

    // Spring Cloud Gateway
    implementation("org.springframework.cloud:spring-cloud-starter-gateway:4.2.1")
    implementation("io.jsonwebtoken:jjwt:0.12.6")

    compileOnly("org.projectlombok:lombok:1.18.38")

    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor:3.4.5")
    annotationProcessor("org.projectlombok:lombok:1.18.38")

    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
