server:
  port: 8080

logging:
  level:
    com.baedal: DEBUG
    com.baedal.gateway.filter: TRACE

jwt:
  secret: my-local-secret-key-should-be-long-enough
  expiration: 1800

  headerName: Authorization
  granted: Bearer

spring:
  cloud:
    gateway:
      routes:
        - id: owner
          uri: http://owner:8087
          predicates:
            - Path=/api/owner/**
          filters:
            - name: PostAuthenticationFilterFactory
              args:
                role: OWNER

        - id: customer
          uri: http://customer:8088
          predicates:
            - Path=/api/customer/**
          filters:
            - name: PostAuthenticationFilterFactory
              args:
                role: CUSTOMER

        - id: rider
          uri: http://rider:8089
          predicates:
            - Path=/api/rider/**
          filters:
            - name: PostAuthenticationFilterFactory
              args:
                role: RIDER

        - id: store
          uri: http://store:8081
          predicates:
            - Path=/api/store/**

        - id: product
          uri: http://product:8082
          predicates:
            - Path=/api/product/**

        - id: cart
          uri: http://cart:8083
          predicates:
            - Path=/api/cart/**

        - id: order
          uri: http://order:8084
          predicates:
            - Path=/api/order/**

        - id: payment
          uri: http://payment:8085
          predicates:
            - Path=/api/payment/**

        - id: review
          uri: http://review:8086
          predicates:
            - Path=/api/review/**
