logging:
  level:
    com.baedal: DEBUG
    com.baedal.gateway.filter: TRACE

jwt:
  secret: my-local-secret-key-should-be-long-enough
  expiration: 1800

  headerName: Authorization
  granted: Bearer

  loginUrlEndsWith: /login

spring:
  cloud:
    gateway:
      routes:
        - id: owner
          uri: http://owner
          predicates:
            - Path=/api/owner/**
          filters:
            - name: PostAuthenticationFilterFactory
              args:
                role: OWNER

        - id: customer
          uri: http://customer
          predicates:
            - Path=/api/customer/**
          filters:
            - name: PostAuthenticationFilterFactory
              args:
                role: CUSTOMER

        - id: rider
          uri: http://rider
          predicates:
            - Path=/api/rider/**
          filters:
            - name: PostAuthenticationFilterFactory
              args:
                role: RIDER

        - id: store
          uri: http://store
          predicates:
            - Path=/api/store/**


        - id: product
          uri: http://product
          predicates:
            - Path=/api/product/**

        - id: cart
          uri: http://cart
          predicates:
            - Path=/api/cart/**

        - id: order
          uri: http://order
          predicates:
            - Path=/api/order/**

        - id: payment
          uri: http://payment
          predicates:
            - Path=/api/payment/**

        - id: review
          uri: http://review
          predicates:
            - Path=/api/review/**
