server:
  port: 9000

logging:
  level:
    com.baedal: DEBUG

jwt:
  secret: my-local-secret-key-should-be-long-enough
  expiration: 1800

spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8080
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
            - name: PreAuthorizationFilterFactory
              args:
                headerName: Authorization
                granted: Bearer
            - name: PostAuthenticationFilterFactory
              args:
                headerName: Authorization
                granted: Bearer

#        - id: rider
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/rider/**
#          filters:
#            - StripPrefix=2
#
#        - id: owner
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/owner/**
#          filters:
#            - StripPrefix=2
